services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    networks:
      - redis_network

volumes:
  redis_data:
  redisinsight_data:

networks:
  redis_network:
    driver: bridge
  