spring:
  config:
    activate:
      on-profile: prod
  devtools:
    add-properties: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authentication?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:P@ssw0rd*123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false


springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

jwt:
  key:
    directory: ${JWT_KEY_DIRECTORY:./keys}
    private_access: ${JWT_KEY_PRIVATE_ACCESS:private_key_access.der}
    public_access: ${JWT_KEY_PUBLIC_ACCESS:public_key_access.der}
    private_refresh: ${JWT_KEY_PRIVATE_REFRESH:private_key_refresh.der}
    public_refresh: ${JWT_KEY_PUBLIC_REFRESH:public_key_refresh.der}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}
